/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as UserIdRouteImport } from './routes/user/$id'
import { Route as BuildCreateRouteImport } from './routes/build/create'
import { Route as UserBuildsRouteImport } from './routes/$user/builds'
import { Route as UserSlugIndexRouteImport } from './routes/$user/$slug/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as UserSlugEditRouteImport } from './routes/$user/$slug/edit'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdRoute = UserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildCreateRoute = BuildCreateRouteImport.update({
  id: '/build/create',
  path: '/build/create',
  getParentRoute: () => rootRouteImport,
} as any)
const UserBuildsRoute = UserBuildsRouteImport.update({
  id: '/$user/builds',
  path: '/$user/builds',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSlugIndexRoute = UserSlugIndexRouteImport.update({
  id: '/$user/$slug/',
  path: '/$user/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSlugEditRoute = UserSlugEditRouteImport.update({
  id: '/$user/$slug/edit',
  path: '/$user/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/$user/builds': typeof UserBuildsRoute
  '/build/create': typeof BuildCreateRoute
  '/user/$id': typeof UserIdRoute
  '/user/': typeof UserIndexRoute
  '/$user/$slug/edit': typeof UserSlugEditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$user/$slug/': typeof UserSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/$user/builds': typeof UserBuildsRoute
  '/build/create': typeof BuildCreateRoute
  '/user/$id': typeof UserIdRoute
  '/user': typeof UserIndexRoute
  '/$user/$slug/edit': typeof UserSlugEditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$user/$slug': typeof UserSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/$user/builds': typeof UserBuildsRoute
  '/build/create': typeof BuildCreateRoute
  '/user/$id': typeof UserIdRoute
  '/user/': typeof UserIndexRoute
  '/$user/$slug/edit': typeof UserSlugEditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$user/$slug/': typeof UserSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/$user/builds'
    | '/build/create'
    | '/user/$id'
    | '/user/'
    | '/$user/$slug/edit'
    | '/api/auth/$'
    | '/$user/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/$user/builds'
    | '/build/create'
    | '/user/$id'
    | '/user'
    | '/$user/$slug/edit'
    | '/api/auth/$'
    | '/$user/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/$user/builds'
    | '/build/create'
    | '/user/$id'
    | '/user/'
    | '/$user/$slug/edit'
    | '/api/auth/$'
    | '/$user/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  UserBuildsRoute: typeof UserBuildsRoute
  BuildCreateRoute: typeof BuildCreateRoute
  UserIdRoute: typeof UserIdRoute
  UserIndexRoute: typeof UserIndexRoute
  UserSlugEditRoute: typeof UserSlugEditRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  UserSlugIndexRoute: typeof UserSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id': {
      id: '/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof UserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build/create': {
      id: '/build/create'
      path: '/build/create'
      fullPath: '/build/create'
      preLoaderRoute: typeof BuildCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$user/builds': {
      id: '/$user/builds'
      path: '/$user/builds'
      fullPath: '/$user/builds'
      preLoaderRoute: typeof UserBuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$user/$slug/': {
      id: '/$user/$slug/'
      path: '/$user/$slug'
      fullPath: '/$user/$slug/'
      preLoaderRoute: typeof UserSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$user/$slug/edit': {
      id: '/$user/$slug/edit'
      path: '/$user/$slug/edit'
      fullPath: '/$user/$slug/edit'
      preLoaderRoute: typeof UserSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  UserBuildsRoute: UserBuildsRoute,
  BuildCreateRoute: BuildCreateRoute,
  UserIdRoute: UserIdRoute,
  UserIndexRoute: UserIndexRoute,
  UserSlugEditRoute: UserSlugEditRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  UserSlugIndexRoute: UserSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
